services:
  - docker

before_install:
  - docker build bvalerin/client_test -f ./client/Dockerfile.dev ./client

script:
  - docker run bvalein/client_test npm test -- --coverage

after_success:
  - docker build -t bvalerin/multi-client ./client
  - docker build -t bvalerin/multi-nginx ./nginx
  - docker build -t bvalerin/multi-server ./server
  - docker build -t bvalerin/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push bvalerin/multi-client
  - docker push bvalerin/multi-nginx
  - docker push bvalerin/multi-server
  - docker push bvalerin/multi-worker
